name: Joint Mining Campaign Proposal
description: Project proposal
title: "[Proposal from]: "
labels: [proposal, triage]
body:
- type: markdown
  attributes:
    value: |
      Projects can submit proposals to get their tokens voted into KyberDMM’s Rainmaker program to receive liquidity mining rewards on top of protocol fees. Please submit your proposal by filling up the necessary details below.
- type: textarea
  id: project-info
  attributes:
    label: Project Introduction
    description: Briefly describe your project and your token.
    placeholder: 
  validations:
    required: true
- type: textarea
  id: key-details
  attributes:
    label: Proposal Summary, Motivation, and Key Details
    description: Briefly summarize how you would like to work with Kyber on the Rainmaker liquidity mining program.
    placeholder: 
  validations:
    required: true    
- type: input
  id: knc-amount
  attributes:
    label: KNC Amount Requested
    description: How many KNC tokens are you requesting for? Please also state the USD value.
    placeholder: 
  validations:
    required: true  
- type: input
  id: token-amount
  attributes:
    label: Project Contribution Amount
    description: How many of your own project tokens do you intend to contribute? Please also state the USD value.
    placeholder: 
  validations:
    required: true 
- type: input
  id: network
  attributes:
    label: Network
    description:  
    placeholder: ex. Ethereum, Polygon
  validations:
    required: true       
- type: dropdown
  id: vesting
  attributes:
    label: Vesting Schedule
    description: Which option you will go for?
    options:
    - No vesting
    - 14 days
    - Other 
  validations:
    required: true
- type: input
  id: duration
  attributes:
    label: Campaign Start date and Duration
    description: 
    placeholder: ex. 2 months, 3 months starting from DD/MM/YYYY
  validations:
    required: true   
