name: Joint Liquidity Mining Proposal
description: Please provide following information to be a part of the ‘Rainmaker’ program for joint liquidity mining with Kyber, using KNC from the ecosystem fund
title: "[Proposal from]: "
labels: [Proposal, triage]
body:
 type: markdown
 attributes: 
value: |

        Please submit your proposals to get your tokens voted into KyberDMM’s Rainmaker program to receive liquidity mining rewards on top protocol fees. Although proposal details may differ depending on the needs of each individual project, all tokens have to fulfil certain criteria based on the liquidity mining framework in order to be eligible for a KyberDAO vote and Rainmaker liquidity mining.Proposals have to be first submitted to Kyber’s governance forum for discussion for 7 days, where the Kyber community will discuss and determine if the project is eligible and what should be a suitable KNC reward allocation.

    - type: input
    id: contact
    attributes:
      label: General Information
      description: How can we get in touch with you if we need more info?
      placeholder: ex. contact information, website url, logo, token contract address, current markets
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please summarize your proposal in 3-4 sentences
      placeholder: Summarize on proposal
      value: "Content suggestion!"
    validations:
      required: true
   - type: input
     id: knc-quantity
     attributes:
      label: KNC Ammount Request
      description: How many KNC estimatedly do you request for in this proposal?
      placeholder: 
    validations:
      required: true
    - type: dropdown
    id: vesting-duration
    attributes:
      label: Vesting Duration
      description: Which option you will go for?
      options:
        - 14 days
        - No vesting
    validations:
      required: true
    - type: input
    id: duration
    attributes:
      label: Campaign Duration
      description: How long should we run the campaign?
      placeholder: ex. 2 months, 3 months, etc
     - type: dropdown
    id: liquidity-mining
    attributes:
      label: Liquidity Mining type
      description: Which type of your liquidity mining
      options:
        - Trade volume
        - Liquidity
    validations:
      required: true
      - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: abc xyz
      options:
        - label: I agree to follow this campaign's Code of Conduct
          required: true
      
