name: Joint Mining Campaign Proposal
description: File a bug report
title: "[Proposal from]: "
labels: [proposal, triage]
body:
- type: markdown
  attributes:
    value: |
      Please provide following information to be a part of the ‘Rainmaker’ program for joint liquidity mining with Kyber, using KNC from the ecosystem fund
- type: textarea
  id: information
  attributes:
    label: General Information
    description: Tell us more about your project
    placeholder: ex. contact information, website url, logo, token contract address, current markets
  validations:
 - type: dropdown
   id: version
   attributes:
    label: Version
    description: What version of our software are you running?
    options:
    - 1.0.2 (Default)
    - 1.0.3 (Edge)
  validations:
    required: true
    required: true
- type: textarea
  id: summary
  attributes:
    label: Summary of your proposal
    description: A summary of what you want to do with the joint mining campaign
    placeholder: summary
    value: content suggestion
  validations:
    required: true
- type: input
  id: knc-quantity
  attributes:
    label: KNC amount request
    description: How many KNC estimatedly do you request for in this proposal?
  validations:
    required: true- type: dropdown
  id: vesting
  attributes:
    label: Vesting circle
    description: Which option you will go for?
    options:
    - No vesting
    - 14 days
  validations:
    required: true

    


      

