name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
    - type: input
    id: contact
    attributes:
      label: General Information
      description: How can we get in touch with you if we need more info?
      placeholder: ex. contact information, website url, logo, token contract address, current markets
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please summarize your proposal in 3-4 sentences
      placeholder: Summarize on proposal
      value: "Content suggestion!"
    validations:
      required: true
   - type: input
     id: knc-quantity
     attributes:
      label: KNC Ammount Request
      description: How many KNC estimatedly do you request for in this proposal?
      placeholder: 
    validations:
      required: true
    - type: dropdown
    id: vesting-duration
    attributes:
      label: Vesting Duration
      description: Which option you will go for?
      options:
        - 14 days
        - No vesting
    validations:
      required: true
    - type: input
    id: duration
    attributes:
      label: Campaign Duration
      description: How long should we run the campaign?
      placeholder: ex. 2 months, 3 months, etc
     - type: dropdown
    id: liquidity-mining
    attributes:
      label: Liquidity Mining type
      description: Which type of your liquidity mining
      options:
        - Trade volume
        - Liquidity
    validations:
      required: true
      - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: abc xyz
      options:
        - label: I agree to follow this campaign's Code of Conduct
          required: true
      
