name: Joint Mining Campaign Proposal
description: 
title: "[Proposal from]: "
labels: [proposal, triage]
body:
- type: textarea
  id: project-info
  attributes:
    label: Project Introduction
    description: Briefly describe your project and your token
    placeholder: 
    value: 
  validations:
    required: true
