name: Joint Mining Campaign Proposal
description: File a bug report
title: "[Proposal from]: "
labels: [proposal, triage]
body:
- type: markdown
  attributes:
    value: |
      Please provide following information to be a part of the ‘Rainmaker’ program for joint liquidity mining with Kyber, using KNC from the ecosystem fund
- type: textarea
  id: information
  attributes:
    label: General Information
    description: Tell us more about your project
    placeholder: ex. contact information, website url, logo, token contract address, current markets
  validations: required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
    - label: I agree to follow this project's Code of Conduct
      required: true
 
