name: Joint Mining Campaign Proposal
description: Project proposal
title: "[Proposal from]: "
labels: [proposal, triage]
body:
- type: markdown
  attributes:
    value: |
      Projects can submit proposals to get their tokens voted into KyberDMM’s Rainmaker program to receive liquidity mining rewards on top of protocol fees. Please submit your proposal by filling up the necessary details below.
- type: textarea
  id: project-info
  attributes:
    label: Project Introduction
    description: Briefly describe your project and your token
    placeholder: 
  validations:
    required: true
